chore: Add Nextcloud 27 support on master
nextcloud/ldap_write_support pull request #561
Opened 2023-03-03 10:39 UTC by nickvergessen

Signed-off-by: Joas Schilling <coding@schilljs.com>

2023-03-03 10:46 UTC, blizzz approved these changes

2023-04-04 07:27 UTC, come-nc requested changes

2023-04-04 07:27 UTC, come-nc commented on package.json
> +	"version": "1.8.0",
Should be the same as in appinfo/info.xml, no?

2023-04-04 09:32 UTC, come-nc commented on package.json
> +	"version": "1.8.0",
```suggestion
	"version": "1.9.0",
```

2023-04-04 11:52 UTC, merged